#!/bin/bash
input_file_name=$1
output_file_name=$2
grep "VmSize"  $input_file_name > VmSize.txt  
grep "VmRSS"   $input_file_name > VmRSS.txt 
grep "Cpu"     $input_file_name > Cpu.txt

awk  '{
	if(NR==FNR) 
		{a[FNR]=$2;} 
	else 
		{a[FNR]=a[FNR]"\t"$2;}
     }

END {print "" >"'"$output_file_name"'"; len=length(a); for (i = 1; i < len; i++) { print a[i]>>"'"$output_file_name"'"}}'  VmSize.txt VmRSS.txt Cpu.txt

rm -f VmSize.txt VmRSS.txt Cpu.txt
