#!/bin/bash

exe_name="IACSvr"
file_name=$exe_name".txt"

echo>$file_name
pid=`pidof  $exe_name | awk '{print $1}'`
echo "pid: " $pid
interval=1
while true
do
        echo $(date +"%y-%m-%d %H:%M:%S") >> $file_name 
        cat /proc/$pid/status|grep -e VmRSS >> $file_name 
	cat /proc/$pid/status|grep -e VmSize >> $file_name 
        cpu=`top -n 1 -p $pid | tail -3 | head -1 | awk '{ssd=NF-4} {print $ssd}'`
        echo "Cpu:      " $cpu >> $file_name 
        echo " " >> $file_name  
        sleep $interval
done
kill -9 $(ps -ef | grep $exe_name| grep -v grep | awk '{print $2}' | tail -1)
